# docker-compose.yml
version: "3.9"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app   # live code reload
    command: poetry run streamlit run app.py --server.address=0.0.0.0 --server.port=8501
